spring.application.name=orders
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5555/shoppingorders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto= none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
shopping.orders.customers.products.url=http://localhost:8081/products
shopping.orders.customers.url=http://localhost:8081/customers
